// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ccps.com/api/ws/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Signature},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/token",
					Handler: GetTokenHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Authorize},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/auth/client",
					Handler: ClientAuthHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/count/client",
					Handler: CountClientHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/join/room",
					Handler: JoinRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/leave/room",
					Handler: LeaveRoomHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/client/list",
					Handler: ClientListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/push/msg",
					Handler: PushMsgHandler(serverCtx),
				},
			}...,
		),
	)
}
