// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
}

type Response struct {
}

type TokenReq struct {
	AccessKey string `form:"access_key,optional" validate:"required"`
}

type TokenRes struct {
	Token string `json:"token"`
}

type ClientAuthReq struct {
	Realm string `form:"realm,optional" validate:"required"`
}

type ClientAuthRes struct {
}

type CountClientReq struct {
	Names   string `form:"names,optional"`
	RoomIds string `form:"room_ids,optional"`
	Tags    string `form:"tags,optional"`
}

type CountClientRes struct {
	Count int64 `json:"count"`
}

type ClientListReq struct {
	Names   string `form:"names,optional"`
	RoomIds string `form:"room_ids,optional"`
	Tags    string `form:"tags,optional"`
}

type ClientListRes struct {
	Name    string   `json:"name"`
	Tags    []string `json:"tags"`
	RoomIds []string `json:"room_ids"`
}

type PushMsgReq struct {
	Names   string `form:"names,optional"`
	RoomIds string `form:"room_ids,optional"`
	Tags    string `form:"tags,optional"`
	Content string `json:"content,optional" validate:"required"`
}

type PushMsgRes struct {
	TotalCount   int `json:"total_count"`
	SuccessCount int `json:"success_count"`
	FailCount    int `json:"fail_count"`
}

type JoinRoomReq struct {
	OptNames   string `form:"opt_names,optional"`
	OptRoomIds string `form:"opt_room_ids,optional"`
	OptTags    string `form:"opt_tags,optional"`
	RoomIds    string `form:"room_ids,optional" validate:"required"`
}

type JoinRoomRes struct {
}

type LeaveRoomReq struct {
	OptNames   string `form:"opt_names,optional"`
	OptRoomIds string `form:"opt_room_ids,optional"`
	OptTags    string `form:"opt_tags,optional"`
	RoomIds    string `form:"room_ids,optional" validate:"required"`
}

type LeaveRoomRes struct {
}
